### ISSUE TITLE
Fix flaky CI

### ISSUE THREAD

**Issue by endophage** [theupdateframework/notary#1028]
We go through periods where Circle is very flaky, mostly due to timing issues of the mysql DB coming up. 

We need to work out how to fix this without increasing how long the CI takes (per the other issue I'm about to file)

**Comment by HuKeping** [comment]
Do we consider to use another framework such as `Travis-CI` to replace the `Circle-CI` if the flaky test is caused by our test code.

**Comment by endophage** [comment]
Unfortunately the flakiness we have control over is largely due to docker. We can try another solution and see if it makes a difference but CircleCI is not directly the cause. It's basically always a problem with MySQL coming up fast enough so it may be worth to try out CircleCI's [services](https://circleci.com/docs/configuration/#services). That will require a few tweaks but should be possible.

Separately we've had all the issues with linux package repos being temporarily unavailable and I don't think moving will have any effect on that.

**Comment by cyli** [comment]
Also TravisCI has been acting up lately on the twisted project with extremely slow build times.  We can switch between the two I guess, and have 2 config files, but looks like that may also not be a permanent solution

**Comment by HuKeping** [comment]
So we may have a try with Circle-CI's services first

**Comment by endophage** [comment]
We haven't seen much flakiness recently. Closing this, can open a new issue if there are specific problems to address again in the future.
