### ISSUE TITLE
Can we use Notary without using Self-Signed Certificates?

### ISSUE THREAD

**Issue by obhabib** [theupdateframework/notary#1230]
Hey guys,

When trying to push images to our internal Harbor registry we get an error `Error: error contacting notary server: x509: certificate signed by unknown authority`

We aren't using self-signed certificates, we use internal CA certs. Is it possible to use notary without using self-signed certs? How should we configure the config.json on the client-side to push to notary. 

Config we using below:
{
  "trust_dir" : "/.docker/trust/",
  "remote_server": {
    "url": "https://internal-docker-registry.com:4443",
    "root_ca": "/opt/notary/config/notary-signer-ca.crt",
    "tls_client_cert": "/opt/notary/config/notary-signer.crt",
    "tls_client_key": "/opt/notary/config/notary-signer.key"
  }
 }

Thanks!

**Comment by cyc115** [comment]
It has been a while since I've done this but I believe you can trust your root ca by putting it into `/usr/local/share/ca-certificates` (in case of ubuntu). [See this](https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu) for more info.

**Comment by endophage** [comment]
@cyc115's option of installing the CA cert in your system roots will work, but you can also point the `root_ca` config option to the path of your CAs root cert.

**Comment by endophage** [comment]
Question answered and there has been no additional discussion so I'm closing this.
