### ISSUE TITLE
Migrate to github.com/theupdateframework

### ISSUE THREAD

**Issue by caniszczyk** [theupdateframework/notary#1249]
As Notary becomes part of CNCF, we need to do a repo transfer to github.com/theupdateframework

**Comment by caniszczyk** [comment]
cc: @endophage

**Comment by endophage** [comment]
Post move checklist:
- [] Update all imports within this repo to use new canonical location
- [] Add notice to top of README stating new location is canonical location going forward
- File issues against known open downstreams that they should update per new location
  - [] github.com/docker/cli
  - [] github.com/kolide/launcher
  - [] github.com/vmware/harbor
- Notify closed source downstreams
  - [] Docker Enterprise Team
- [] Update Docker Hub official image docs to point at new location https://github.com/docker-library/docs

**Comment by marpaia** [comment]
Hey @endophage, thanks for letting us know about this (https://github.com/kolide/launcher/issues/196)! I think this should not be a problem, we should be able to easily update the imports both here and in https://github.com/kolide/updater to account for the new repo path when you all make the switch. Is there anywhere we can subscribe to / any slack channel we can join to get more details on this process as it happens to make sure we can update everything as soon as possible?

**Comment by endophage** [comment]
Hey @marpaia. If it's useful I can post updates to the #notary channel in dockercommunity.slack.com

The main events will be the move itself, then the merging of the PR that updates all the internal imports (which I or one of my team mates will be creating shortly).

As you're pinned to a specific version though, and GH will put a redirect in place when we make the move, there should be no rush to update. My current timing on the move is to try and make it happen early afternoon PST tomorrow (Oct 26th), but certainly by the end of this week.

**Comment by marpaia** [comment]
I know GitHub will redirect repos when you move/rename them, I've never tested the GitHub redirect with actual Go dependency management tools, but if it respected the redirect, that would be great. I was going to suggest forking the new repo back to the original path, but if the redirect works, it obviously wouldn't be necessary.

**Comment by endophage** [comment]
Tests on #1252 are green. Planning to do the move in the 2-3pm PST timeframe once I've had a chance to get lunch, just in case something goes wrong :-P

**Comment by endophage** [comment]
Move done, waiting on CircleCI (had to be reconfigured) to confirm the PR with the import renaming passes tests https://circleci.com/gh/theupdateframework/notary/5072

If that's green, I'll merge it to master (which should make master fully functional in this new location), and work on getting any other bits and pieces cleaned up

**Comment by endophage** [comment]
While we're waiting on CircleCI, I've set up a team within theupdateframework org for the maintainers called "Notary Maintainers", sent invitations to the notary maintainers to join that team, and made the team an admin of this repo.

**Comment by endophage** [comment]
Move should be considered complete. Working on connecting up our Jenkins job that tests the master branch which will push codecov back up to ~81%. Otherwise, we're looking good.
