### ISSUE TITLE
Outdated CLI release

### ISSUE THREAD

**Issue by spielkind** [theupdateframework/notary#1266]
It seems that the notary client release (0.4.3) could you create a new release? Or is version 0.5.1 not a stable release?

**Comment by endophage** [comment]
0.5.x was a somewhat special version that we didn't want to generally support. We're working on a 0.6.0 release that will be supported.

**Comment by sjhx** [comment]
Whats the outlook for 0.6.0?

**Comment by cyli** [comment]
Just released today if you wanted to check it out, @spielkind

**Comment by cyli** [comment]
Closing this issue, as 0.6.0 just came out.  If you find any issues with the release, please feel free to file one or more new issues!
