### ISSUE TITLE
[NOTARY] Can’t sign and pushing metadata

### ISSUE THREAD

**Issue by gmaurelia** [theupdateframework/notary#1270]
Hi everyone,

I have Notary configured as a service and when doing a docker push, after delegating, I get the following error message:

````ERRO [0000] could not add target to targets / releases: at least one of these keys must be available: 44c1cc4d2d185000e85585779920ce1bc7d8c2f72724b739b3304915e536d971
Failed to sign "my.registry: 443 / images / nginx-conf": v2 - could not find necessary signing keys, at least one of these keys must be available: 44c1cc4d2d185000e85585779920ce1bc7d8c2f72724b739b3304915e536d971
Error: could not find signing keys for remote repository my.registry: 443 / images / nginx-conf, or could not decrypt signing key: could not find necessary signing keys, at least one of these keys must be available: 44c1cc4d2d185000e85585779920ce1bc7d8c2f72724b739b3304915e536d971
````

I do not know what I’ll be doing wrong, since I’ve been guided through this [video]
(https://blog.docker.com/2016/03/notary-0-2/) and after adding a delegate, I copied the key to the host delegate on which I want to do a docker push and the message error appears.

I hope you can guide me if someone else has happened to you.

Greetings.

**Comment by gmaurelia** [comment]
The problem I had was that before I docker push, I applied the command: **notary init my.registry:443/collection** so notary generated a collection with different keys and in this way I could not do push docker of any image under any role nor even targets.

Once I did it the right way, I applied the steps you mentioned to me and the problem was solved. The notary configuration is the following:

command: tree $HOME/.docker/trust/

.docker/trust
├── certs
│   ├── delegation.crt
│   └── proof
│       ├── delegation.crt
│       ├── delegation.csr
│       └── delegation.key
├── config.json
├── private
│   ├── root_keys
│   │   └── 4e46a197de40621094f86e0cea4aa892d7c3cfb1b3400c64f6d7d82e4b97a470.key
│   └── tuf_keys
│       ├── 3269a0858ca91001c543435d0242e747bd08e68b52533f1b42028388ed02c7e6.key
│       └── my.registry:443
│           └── galera-leader-proxy
│               └── 
|           873ba8267df2be149fba2230441961812159c35537b18c133247239f4bafa989.key
├── root-ca.crt
├── tls
│   └── my.registry:443
│       └── root-ca.crt
└── tuf
    └── my.registry:443
        └── galera-leader-proxy
            ├── changelist
            └── metadata
                ├── root.json
                ├── snapshot.json
                ├── targets
                │   ├── kube1.json
                │   └── releases.json
                ├── targets.json
                └── timestamp.json

On the other hand, to configure the client correctly I defined the following alias:

alias dockernotary="notary -c $HOME/.docker/trust/config.json -d $HOME/.docker/trust/ -s https://notary-server:4443"

Saludos.

**Comment by cyli** [comment]
Thanks for resolving this @gmaurelia

**Comment by anekar10** [comment]
Can you please mention the steps that you followed, as that video is not available anymore. 
I am getting the same error, I was able to sign it the first time. Singing the same image with a different tag, gives this issue. Not sure what I can do here
