### ISSUE TITLE
RSA besides of ECDSA for all keys (root,target,etc)

### ISSUE THREAD

**Issue by florianeichin** [theupdateframework/notary#1277]
Is there a possibility to use only rsa keys instead of ecdsa keys in notary? As I investigated the codebase, I saw, that `notary key generate rsa` results in an error. 
Are their reasons for that or is it just not yet implemented?

**Comment by ecordell** [comment]
You can see the PR here: https://github.com/theupdateframework/notary/pull/1191

Perhaps @endophage knows why RSA was dropped; I don't see the reasoning in that PR. You can still generate RSA keys externally and import them, however.
