### ISSUE TITLE
Possibility of race condition when multiple notary server write to the same DB?

### ISSUE THREAD

**Issue by cyc115** [theupdateframework/notary#1278]
Assuming you have multiple servers backed by the same Server DB and multiple clients decides to publish incompatible metadata at the same time (eg. different tuf data with the same version number). Can I expect that only one publish will succeed and the rest will fail? 

Looking at `server/storage/sqldb.go#UpdateCurrent()#L74` a transaction is created to guarantee the atomicity of row creation. But this does not check the version number we want to create is the highest version number in the database. Therefore if Client `A` publishes `v4` of a metadata, client `B` could still publish the same version with different data if both publish happens at almost the same time? 

Please let me know if I am missing something. 👍 
Thanks in advance.

**Comment by ecordell** [comment]
```
 UNIQUE KEY `gun` (`gun`,`role`,`version`)
``` 
There's a unique index on (gun, role, version) which will ensure only one of the two transactions will win. (the next will start and be unable to commit).

**Comment by cyc115** [comment]
Thank you @ecordell !
