### ISSUE TITLE
non interactive authentication 

### ISSUE THREAD

**Issue by sjhx** [theupdateframework/notary#1292]
the notary client currently only accepts authentication credentials interactively 
this is not a great user experience if the credentials are not user / password  (even if they are)
in the case where the credentials are some kind of bearer token it would be better to be able to 
store them in the environment or in another local store of some kind such that the user is not troubled by on invocation

**Comment by eiais** [comment]
Notary has environment variables to help with automation if that's what you're looking for. 
https://github.com/theupdateframework/notary/blob/7d89062d97dc59b276f1d5553d3ca66ce959b5c3/docs/reference/client-config.md#environment-variables-optional

**Comment by HuKeping** [comment]
Thanks @eiais ! It seems the [Environment variables parts](https://github.com/theupdateframework/notary/blob/7d89062d97dc59b276f1d5553d3ca66ce959b5c3/docs/reference/client-config.md#environment-variables-optional)  is what your need @sjhx ?

**Comment by sjhx** [comment]
I do not think the current environment variables satisfy the need I raised, I believe they enable the trust  passphrases to be passed non-interactively whereas I am asking for the ability to authenticate with the notary server, i.e. to authenticate the notary request non-interactively.

**Comment by cyli** [comment]
Many apologies we just hadn't documented it yet.  https://github.com/theupdateframework/notary/pull/1246 added a `NOTARY_AUTH` environment variable for authentication credentials.

**Comment by ericsmalling** [comment]
@cyli I don't think doc's ever got done on this or am I just missing it?

**Comment by eiais** [comment]
@ericsmalling https://github.com/theupdateframework/notary/blob/master/docs/reference/client-config.md#environment-variables-optional NOTARY_AUTH is the last one on the list. Both of the other links in this thread linked at a specific commit instead of what is on master.

**Comment by ericsmalling** [comment]
Thanks @eiais - I must have missed it.
