### ISSUE TITLE
queries on public repos ask for auth on HEAD

### ISSUE THREAD

**Issue by justincormack** [theupdateframework/notary#1296]
on a HEAD build (on OSX) I get prompted for a username and password just querying public repositories eg `./bin/notary -s https://notary.docker.io -d ~/.docker/trust list docker.io/library/alpine`. This does not happen on the current release versions.

```
whale:notary justin$ ./bin/notary version
notary
 Version:    0.5.0
 Git commit: 9763f6f2
```

**Comment by cyli** [comment]
Oops sorry @justincormack - I think this is because of https://github.com/theupdateframework/notary/issues/1308.

**Comment by justincormack** [comment]
Yes this does seem to be the same issue.
