### ISSUE TITLE
repo key password not recognized in 0.6.0?

### ISSUE THREAD

**Issue by BillMills** [theupdateframework/notary#1310]
With release 0.6.0 installed locally, I set up content trust for my DTR (2.5.0-beta3) repo as follows:

```
notary init -p ${DTR_FQDN}:4443/demo/xyz
```

everything seemed to work perfectly; it asked me to generate key passphrases as usual. Then, when I pushed an image to DTR, it would not accept my passphrase for my repo key.

Everything worked correctly and as usual after installing release 0.4.3.

fyi:
```
[centos@ucp-manager-0 ~]$ uname -a
Linux ucp-manager-0 4.14.11-1.el7.elrepo.x86_64 #1 SMP Tue Jan 2 19:16:00 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cyli** [comment]
@BillMills Which version of Docker are you using?

**Comment by BillMills** [comment]
```
[centos@ucp-manager-0 ~]$ docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:43:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:45:16 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by cyli** [comment]
@BillMills Apologies, the key encryption format has changed as of 0.6.0, which is not forwards compatible with 0.4.3.  It should also have specified not forwards-compatible with Docker < 17.12.  So notary 0.6.0 can read keys generated using previous versions of notary and docker, but older versions of notary and docker cannot read keys generated by 0.6.0.

I'll update the changelog and release notes with the docker version.  Could you please continue to use 0.4.3 with 17.06.x docker?

**Comment by BillMills** [comment]
Will do, thanks @cyli!
