### ISSUE TITLE
Update CircleCI to V2

### ISSUE THREAD

**Issue by tylerauerbeck** [theupdateframework/notary#1316]
CircleCI is deprecating V1 syntax: https://circleci.com/blog/sunsetting-1-0/

We should update to V2 to avoid running into issues at the deprecation date.

**Comment by cyli** [comment]
@thaJeztah Yes - the notary circle one is going to be trickier, because we use compose.

**Comment by justincormack** [comment]
fixed for now in #1395 - need to improve paralellism though still.
