### ISSUE TITLE
Questions about Notary

### ISSUE THREAD

**Issue by LionHeart7735** [theupdateframework/notary#1392]
Hi,

May i know Notary can work without Docker registry ? I saw a lot of example Notary with Docker registry.
How about other file formats like jar file? 

My requirement need file integrity check system hosted behind my company firewall. We generate private/public key pair for jar file and pass public key and jar file to client. Client connects to our integrity check system using the public key to check jar file integrity.

May i know Notary is what i want base on above requirement ? If yes, any examples ?

Appreciate for any advice

Jason

**Comment by HuKeping** [comment]
> May i know Notary can work without Docker registry ? I saw a lot of example Notary with Docker registry.

Yes, absolutely.

**Comment by LionHeart7735** [comment]
Hi HuKeping

May I know what is the command for client to check the jar file integrity ? I cant find example for this. 
May you direct me to the API page ? 
Appreciate for any advice

Thank You 
Jason

**Comment by LionHeart7735** [comment]
> First you need to run an [service](https://github.com/theupdateframework/notary/blob/master/docs/running_a_service.md) of `notary server` and `notary signer`which will provide you the functionalities of Notary. I think there is already a docker image for it, but it's fine if you do not want to running the service in docker container.
> 
> After that, using [Notary CLI](https://github.com/theupdateframework/notary/blob/master/docs/getting_started.md) to do everything you want( sign , verify, etc)

Thanks for reply. btw, i able to run an service of notary server and notary signer using docker-compose but i cannot initialize collection : 

 notary init example.com/collection

where should i issue command above ?

Thanks for any advice!
Jason

**Comment by HuKeping** [comment]
What's the error

**Comment by LionHeart7735** [comment]
Hi HuKeping,

What is the necessary change for me to run docker-compose in docker for windows version ?
I hit below error :+1:
 `sh: ./migrations/migrate.sh: not found`
in both server and signer container. 

Appreciate for any advice

Thank You
Jason
