### ISSUE TITLE
Several signatures on one single target?

### ISSUE THREAD

**Issue by flsou-e** [theupdateframework/notary#1404]
Hi,

I am new to notary, and I am looking forward to sign one target with multiple signatures. In my workflow, each of these signatures matches one step (e.g. 1 signature for build step, 1 signature for QA step).

For now, I could not succeed in implementing this workflow with notary CLI commands. I even tried to add notary delegations, although I am not sure it would help.

Could you explain how this could be done?

Thanks!

**Comment by eiais** [comment]
Hello,
If you want to sign for each step in your process, you'll want to create a delegation role for each step and have them sign after they've confirmed their bit. (e.g. the builder signs it to assert who built it. QA signs it after it has gone through QA)

**Comment by flsou-e** [comment]
Hi!
Ok so I could have mistaken when tried to deal with delegation roles.
Thanks for the answer, I will continue my experiments with that way.
