### ISSUE TITLE
How can I tell or pass notary key import command key passphrase

### ISSUE THREAD

**Issue by m4masood** [theupdateframework/notary#1406]
Hi,

I have set NOTARY_ROOT_PASSPHRASE environment variable and calling $ notary key import my_delegation.key

but notary kept prompting me for passphrase.
Is there a way we can tell notary to use some passphrase in CI environment?

Thanks,
Muhammad

**Comment by justincormack** [comment]
See https://docs.docker.com/engine/security/trust/trust_automation/ you need `DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE` set.

**Comment by justincormack** [comment]
(we should move these docs to this repo).

**Comment by justincormack** [comment]
there is `NOTARY_DELEGATION_PASSPHRASE` and `NOTARY_AUTH` environment variables too.

**Comment by mmasooddatascience** [comment]
Even setting DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE and NOTARY_DELEGATION_PASSPHRASE, notary still prompts for passphrase for key.

![image](https://user-images.githubusercontent.com/7548298/49339560-19954c00-f688-11e8-8fd5-0d60850b0179.png)

Any idea?

**Comment by BertieW** [comment]
Having the same issue. I searched for all the possible env vars in the notary repository and tried every single one and it still prompts for a password.

**Comment by m4masood** [comment]
Any updates on this?

**Comment by m4masood** [comment]
Any updates on this?

**Comment by dubo-dubon-duponey** [comment]
@m4masood 

I can confirm that using `$ NOTARY_ROOT_PASSPHRASE="foo" notary WHATEVER` works as expected and that notary does NOT ask for the root passphrase interactively.

Are you sure:

 * you are setting the environment variable correctly?
 * you have the right password, for the existing root key?

**Comment by m4masood** [comment]
Thanks looks like its working.
