### ISSUE TITLE
how can I install notary binary in ubuntu?

### ISSUE THREAD

**Issue by m4masood** [theupdateframework/notary#1407]
Hi,

I installed notary using apt-get and when I checked the version I get blank like shown below:
![image](https://user-images.githubusercontent.com/7548298/49350203-32424800-f702-11e8-8549-605dc87ee5d4.png)

So I want to install notary package from https://github.com/theupdateframework/notary/releases in ubuntu machine to know exactly which version of notary I am running. How can I do that using package/binary mentioned in releases?

Thanks,
Muhammad

**Comment by eiais** [comment]
Hi Muhammad,
Notary doesn't have an official deb package. If you want to use the exact binary from the release you can download it from github.
