### ISSUE TITLE
x509 cert errors using notary playground instructions

### ISSUE THREAD

**Issue by jondkent** [theupdateframework/notary#1417]
I getting the same error reporting a few years back and resolved (https://github.com/theupdateframework/notary/issues/949).  Seems to have resurfaced

/ # docker pull sandboxregistry:5000/test/trusttest
Using default tag: latest
Error: error contacting notary server: x509: certificate has expired or is not yet valid
/ #

**Comment by jondkent** [comment]
I was following the instructions as outlined here - https://docs.docker.com/engine/security/trust/trust_sandbox/

The compose file outlined there points to dockersecurity/notary_autobuilds:server-v0.4.2 which I assume is what holds the cert

**Comment by justincormack** [comment]
Yes that is a very old build, not surprising that the certificates have expired. The new version is `notary:server-0.6.1-1` not sure if it has the certs in the same place but may well do.

**Comment by jondkent** [comment]
I've now tried every version listed  on DockerHub and aside from 0.4.2  (the version with the out of date cert), the docker:dind containers all fail with a missing cert file error:

`docker logs 455ae7968ddab9d8471c08006f44900b4ae02aeae6c0c4c97151ca7e0829f1d1
cp: can't stat '/notarycerts/root-ca.crt': No such file or directory`

The version you mention I don't see listed when I look at the tags on https://hub.docker.com/r/dockersecurity/notary_autobuilds/tags

**Comment by jondkent** [comment]
OK,figured this out.

In the example docker-compose config the shared volume between the notary container and the dind container is defined as:

` - notarycerts:/go/src/github.com/docker/notary/fixtures`

This works fine for version 0.4.2, however for 0.5.1 the cert location has changed and the volume needs to be defined as:

`- notarycerts:/var/lib/notary/fixtures`

And then it appears to work(note I haven't finished testing the sandbox yet).

Me thinks the documentation need an update here :-)

**Comment by jondkent** [comment]
I can confirm that with the above changes I can now sign an image and pull that image.

**Comment by jondkent** [comment]
Raised a PR for the documentation updated

https://github.com/docker/docker.github.io/pull/8182

**Comment by jondkent** [comment]
Closing as PR merged
