### ISSUE TITLE
Question about the definition of version

### ISSUE THREAD

**Issue by csqshz** [theupdateframework/notary#1433]
Hi all,
By using " git tag ", I found that there were several definitions of version.
I am confused with v0.6.1 and docker-v1.11-3. 

My questions are:
1. Which is the mainline version, v0.6.1 or docker-v1.11-3 or other ?
2. Does the docker-v1.11-3 is based on the version of golang ?
3. Which version should I chose, I just want to integrate the newest version to my system.

Thanks.

**Comment by thaJeztah** [comment]
v0.6.1 is what you're looking for, the `docker-` tags were used to tag releases to align with docker releases (e.g. docker v1.11)

**Comment by justincormack** [comment]
Yes, all the `docker-` releases are obsolete. There are a bunch of branches and tags that should probably be cleaned up.

**Comment by csqshz** [comment]
> v0.6.1 is what you're looking for, the `docker-` tags were used to tag releases to align with docker releases (e.g. docker v1.11)

Thank you very much.

**Comment by csqshz** [comment]
> Yes, all the `docker-` releases are obsolete. There are a bunch of branches and tags that should probably be cleaned up.

Thank you very much.
