### ISSUE TITLE
How can i enable DCT on my infra with nexus as private registory

### ISSUE THREAD

**Issue by abhi-dwivedi** [theupdateframework/notary#1441]
Hi,

How can i enable DCT on my infra with nexus as private registry

Regards
Abhinav D

**Comment by abhi-dwivedi** [comment]
Any Update

**Comment by HuKeping** [comment]
Will [this doc]( https://github.com/theupdateframework/notary#getting-started-with-the-notary-cli) help ?

**Comment by abhi-dwivedi** [comment]
Hi HuKeping

Thanks for your response.
I have setup the notary infra and i am able to push the docker image with signed from root and repo key.
But how can i pull that signed image. Becuse when i pull its just pull the image without the trusted key.
i checked from "docker trust inspect image:tag"

**Comment by HuKeping** [comment]
Have you exported these two environment: 
 - `DOCKER_CONTENT_TRUST=1` 
 - `DOCKER_CONTENT_TRUST_SERVER=https://your-notary-server`

**Comment by abhi-dwivedi** [comment]
HI,

These two variable exposed in Docker push server and i am pulling the image from another server

**Comment by HuKeping** [comment]
Let's say you have a push-machin A,  pull-machine B, and the address of docker registry is example.com, the address of notary server is `example.com/notary-server`, the image name(GUN) is `example.com/image:latest`.

The workflow would like to be:
1.  On machine A: 
- export DOCKER_CONTENT_TRUST=1
- export DOCKER_CONTENT_TRUST_SERVER=example.com/notary-server
- docker push example.com/image:latest  

2. On machine B:
- export DOCKER_CONTENT_TRUST=1
- export DOCKER_CONTENT_TRUST_SERVER=example.com/notary-server
- docker pull example.com/image:latest

**Comment by abhi-dwivedi** [comment]
Hi

So i need to make my notary server available to all Pull machine correct?

Or I need to do docker-compose for creating container of notary server in all Machine B pull machine?

Regards
Abhinav

**Comment by HuKeping** [comment]
Just make it available to all your pull machine

**Comment by abhi-dwivedi** [comment]
Hi

Thanks Let me do that if found any issue will update you .

Regards
Abhinav

**Comment by abhi-dwivedi** [comment]
Hi

So when i Push the image on my private repo i am getting cert error "Error: error contacting notary server: x509: a certificate signed by an unknown authority" so when i create a directory under /root/.docker/tls/notary-server:4443 and then copy the root-ca.crt file which is provided in notary directory.
Then i am able to push. But when i am pulling the image as you mention it gives me same cert error

**Comment by HuKeping** [comment]
Haven't got a time slot to run it from scratch , would you mind to try deploy the notary-server under the http(not `https`) protocol, I guess the error you get may not caused by notary.

**Comment by abhi-dwivedi** [comment]
But if i remove the https does it sign the image properly?

**Comment by abhi-dwivedi** [comment]
getting this error after configuring it without https

error establishing connection to trust repository: valid https URL required for trust server, got http://notary-server:4443

**Comment by abhi-dwivedi** [comment]
Hi HuKeping 

Could you please update the thread i am stuck now?

**Comment by HuKeping** [comment]
> The similar issue at #937

Seems like the same problem.

**Comment by abhi-dwivedi** [comment]
HI

But that's different issue i have to use notary server without https .
Could you help me to configure it

**Comment by abhi-dwivedi** [comment]
hi HuKeping

Could you help me to configure it

**Comment by justincormack** [comment]
Notary requires https, it does not support an http configuration.

**Comment by abhi-dwivedi** [comment]
Hi justin

Same question for you
So when i Push the image on my private repo i am getting cert error "Error: error contacting notary server: x509: a certificate signed by an unknown authority" so when i create a directory under /root/.docker/tls/notary-server:4443 and then copy the root-ca.crt file which is provided in notary directory.
Then i am able to push. But when i am pulling the image as you mention it gives me same cert error

So every time on the pull host i need to add this cert??

**Comment by abhi-dwivedi** [comment]
HI

Any update??

**Comment by HuKeping** [comment]
oops, sorry, @abhi-dwivedi , @JustinCappos just correct me that notary does not support http

**Comment by dubo-dubon-duponey** [comment]
@abhi-dwivedi 

> So every time on the pull host i need to add this cert??

Yes

I assume you are using a self-signed TLS cert?

If you really don't want to copy over your cert, buy a certificate from a CA that is trusted by your hosts systems.

**Comment by justincormack** [comment]
seems resolved.
