### ISSUE TITLE
Is it possible to define --configFile parameter with env vars?

### ISSUE THREAD

**Issue by adomenech73** [theupdateframework/notary#1462]
My problem comes when using notary or Docker content trust from a Jenkins pipeline, for some strange reason, that I don't get, it doesn't find the default configuration files.

I can easily solve this when using notary directly, adding ```--configFile ~/.notary/config.json```to the command, but I don't know how to do this when using notary through docker content trust like:
```docker trust sign...``` or ```docker push...```

**Comment by justincormack** [comment]
`docker trust` does not support Notary config files at all. If you need different features in it please open issues at https://github.com/docker/cli

For the Notary case, are you running with `sudo` or something such that `~` is not pointing where you expect?

**Comment by adomenech73** [comment]
Thanks for your quick response and sorry for the misunderstood

Actually, I'm using an unprivileged user

I think that the problem should be related to jenkins pipeline because if I execute from shell everything just works as expected, but I'm a bit lost about where I can ask for help as there are multiple pieces involved.

But from the pipeline if I execute ```notary key list```I get ```No signing keys found.```
If I execute ```notary --configFile ~/.notary/config.json key list``` I get the expected output, being ~=/var/lib/jenkins

So I was hopping to have something like ```--configFile``` available at docker trust level, I made some tests with DOCKER_CONFIG env var, but it doesn't seem to solve the issue in this case
