### ISSUE TITLE
Is Notary under Active Development?

### ISSUE THREAD

**Issue by raesene** [theupdateframework/notary#1467]
Just a general question, as I can't find anything official on blogs or documentation.  Is Notary still being actively developed?  

Looks like the last release was in April 2018 and there's no release addressing some upstream golang security issues (https://github.com/theupdateframework/notary/pull/1420 isn't merged.)

**Comment by justincormack** [comment]
Hi, yes there is still active development. We do currently have a shortage of active maintainers though, which is something we are looking to improve.

**Comment by raesene** [comment]
Cool, Thanks for the update :)
