### ISSUE TITLE
Bug: Compatible fix for API change of `github.com/docker/distribution@v2.7.1`

### ISSUE THREAD

**Issue by SimonXming** [theupdateframework/notary#1469]
I'm developing a library base on notary. When I running `go test`, Following error raised:
```
# github.com/theupdateframework/notary/utils
../../../../pkg/mod/github.com/theupdateframework/notary@v0.6.1/utils/http.go:112:24: not enough arguments in call to challenge.SetHeaders
	have (http.ResponseWriter)
	want (*http.Request, http.ResponseWriter)
```
Currently, `notary` is using `github.com/docker/distribution@v2.7.1`, and compared to `github.com/docker/distribution@v2.6.x`, the function signature of `challenge.SetHeaders()` has changed. Looks like the `vender` directory is outdated.

**Comment by dubo-dubon-duponey** [comment]
@SimonXming Not sure I understand.

Notary does vendor distribution 2.7.1, and this is exactly what is in the vendor directory:

https://github.com/theupdateframework/notary/blob/v0.6.1/vendor/github.com/docker/distribution/registry/auth/auth.go#L91

**Comment by SimonXming** [comment]
@dubo-dubon-duponey, I think the docker/distribution 2.7.1 is not vendered. Please check https://github.com/docker/distribution/blob/v2.7.1/registry/auth/auth.go#L83-L91

**Comment by elboulangero** [comment]
Hitting the same issue. Nothing to add, @SimonXming described the problem accurately.

**Comment by cpaelzer** [comment]
I this not also [hits Ubuntu/Debian builds](https://bugs.launchpad.net/ubuntu/+source/notary/+bug/1851695) of notary, but my go-foo is far too low to provide mcuh more to the case.

**Comment by justincormack** [comment]
Yes, we seem to have a slightly older version from master, opening a PR yo update.

**Comment by HuKeping** [comment]
Closing via #1514
