### ISSUE TITLE
Understanding Delegation Keys

### ISSUE THREAD

**Issue by gsexton** [theupdateframework/notary#1470]
I'm having trouble understanding delegation keys, and I hope someone can help me.

I would like to have a GUN:

my-registry.example.com/projname

I would like to setup a delegation key that would sign anything under my-registry.example.com/projname

I can create the key and it gets used. What seems to happen though is that if I sign:

my-registry.example.com/projname/foo:latest

and 

my-registry.example.com/projname/bar:latest

Docker/Notary seem to create a repository key for each  path. E.G. a key for /projname/foo, and another key for /projname/bar

At each docker push, I'm prompted for the root key and it creates a new repository key.

I've really gone through the docs and played with this extensively. Is there any way that I can use delegations for all paths that are used in signing, or are delegation keys really restricted down to one path, e.g. /projname/foo.

My goal is to be able to use this in Jenkins, so I can't have the operator be prompted constantly for creation of a new repository key.

I really appreciate any insights. I'm sure there's something dumb that I'm not getting, but I've really given it a try.

Thanks.

George

**Comment by dubo-dubon-duponey** [comment]
> My goal is to be able to use this in Jenkins, so I can't have the operator be prompted constantly for creation of a new repository key.

You could specify environment variables for the passwords you want for the repo keys so not to be prompted when keys are created for new repos.

```
NOTARY_ROOT_PASSPHRASE=REPLACEME NOTARY_TARGETS_PASSPHRASE=REPLACEME NOTARY_SNAPSHOT_PASSPHRASE=REPLACEME notary WHATEVER
```

**Comment by gsexton** [comment]
I guess this was a lack of understanding on my part. What I didn't realize, and the docker/notary docs don't make really clear is that each target is a unique GUN with a unique targets key.

so, 
/project/name/foo
/project/name/bar

are two distinct GUNs, and the root key must be available to sign a target key or do delegation for each. I can see where this is OK if you don't have a large number of targets, but if you're in a large organization, with dozens or hundreds of targets, it gets out of hand pretty quickly. I'm looking at creating a web service that will do nothing but do this. The web service is necessary so that the ROOT key isn't exposed.
