### ISSUE TITLE
undefined: possiblePkcs11Libs (Windows installation)

### ISSUE THREAD

**Issue by nicolas-mosch** [theupdateframework/notary#1495]
When trying to install notary client with the command `go install -tags pkcs11 github.com/theupdateframework/notary/cmd/notary` I get the following error:

`# github.com/theupdateframework/notary/trustmanager/yubikey
go\src\github.com\theupdateframework\notary\trustmanager\yubikey\yubikeystore.go:95:22: undefined: possiblePkcs11Libs`

Googling the error returned nothing. Is it even possible to install it on windows?

**Comment by nicolas-mosch** [comment]
Using the latest release for windows worked fine

**Comment by sfxworks** [comment]
I also get this issue. Using the latest release did not work for me.
