### ISSUE TITLE
notary@v0.6.1 cannot be used as a module anymore

### ISSUE THREAD

**Issue by cfiderer** [theupdateframework/notary#1542]
Since February 25, 2020, the github.com/agl/ed25519 repository doesn't exist anymore. It is, however, still referenced in the latest (v0.6.1) release of notary.

The necessary changes in the notary code (d4f8e4a, 0ec845d) were already done on April 16, 2018 - just a week after the v0.6.1 release.

When will a new release become available?

**Comment by marcofranssen** [comment]
Yup figured that today when I did a `go get -u`. I have filed another issue suggesting the same #1564

**Comment by cfiderer** [comment]
@justincormack Any chance that we get a new release in the near future?

**Comment by justincormack** [comment]
Yes I am planning a release shortly, just got a few things to merge and update.

**Comment by pigletfly** [comment]
any updates?

**Comment by HuKeping** [comment]
Fixed by #1585
