### ISSUE TITLE
Since 2018 there hasn't been a new release

### ISSUE THREAD

**Issue by marcofranssen** [theupdateframework/notary#1564]
Could there be done a new release?

I'm using some of the code as a library in my own solution. I figure 0.6.1 lacks still a whole bunch of code which is currently on the master branch.

Would be great if there can be done a more recent release so I can point to that version, as well to have some of the indirect dependencies also nicely updated.

Maybe it even makes sense to release a whole bunch of versions on specific commits, to give some more possibilties for others to pick a version they require.

For now I'm working with `replace` statement and submodule in my `go.mod`.

**Comment by HuKeping** [comment]
Fixed by #1585
